// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void BundleConfig.RegisterBundles(BundleCollection bundles)', validate parameter 'bundles' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.BundleConfig.RegisterBundles(System.Web.Optimization.BundleCollection)")]
[assembly: SuppressMessage("Build", "CA3147:Missing ValidateAntiForgeryTokenAttribute on MVC controller action Index which by default accepts POST requests", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.Controllers.HomeController.Index~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'PowerShell.Create()' before all references to it are out of scope", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.Controllers.HomeController.Index(System.String)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'ActionResult HomeController.Index(string target)', validate parameter 'target' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.Controllers.HomeController.Index(System.String)~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Build", "CA3147:Missing ValidateAntiForgeryTokenAttribute on MVC controller action Results which by default accepts POST requests", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.Controllers.HomeController.Results~System.Web.Mvc.ActionResult")]
[assembly: SuppressMessage("Build", "CA2000:Call System.IDisposable.Dispose on object created by 'new PSDataCollection<PSObject>()' before all references to it are out of scope", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.Controllers.PowershellController.RunScript(System.Management.Automation.PowerShell,System.Boolean)")]
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void FilterConfig.RegisterGlobalFilters(GlobalFilterCollection filters)', validate parameter 'filters' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:RealtimePowerShellHTMLWindow.FilterConfig.RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)")]
[assembly: SuppressMessage("Build", "CA1052:Type 'BundleConfig' is a static holder type but is neither static nor NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:RealtimePowerShellHTMLWindow.BundleConfig")]
[assembly: SuppressMessage("Build", "CA1052:Type 'FilterConfig' is a static holder type but is neither static nor NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:RealtimePowerShellHTMLWindow.FilterConfig")]
[assembly: SuppressMessage("Build", "CA1052:Type 'RouteConfig' is a static holder type but is neither static nor NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:RealtimePowerShellHTMLWindow.RouteConfig")]
